### ISSUE TITLE
Documentation for the showcase command

### ISSUE THREAD

**Issue by HeroicKatora** [kangalioo/rustbot#11]
It's hardly clear to me what it will actually do when invoked.
Will a thread show up immediately? Where must the information be provided?
Why do none of the _current_ showcase entries have a proper description or links like the used to? User error?

**Comment by kangalioo** [comment]
I agree, the help text and guiding messages weren't well thought out.

Since last deploy, the help text was already changed from

> Post your project in the #showcase channel. You will be asked to fill out some information about the project.

to

> Starts a prompt where you can enter information about a project you're working on. The bot will then post your project into the #showcase channel and open a thread to allow for discussion
 and feedback.
> 
> If you want to change the text later, edit your message and the bot will propagate the change.

And the confirmation message from

> Your project was successfully posted in #showcase

to

> Your project was successfully posted in #showcase. To change the text later, edit the messages you sent and the bot will propagate the changes.

I'm open for further suggestions :)

What do you mean with "proper description or links like they used to"? The showcase entries do have descriptions and links

**Comment by HeroicKatora** [comment]
> What do you mean with "proper description or links like they used to"? 

Well, that's what I see…

![cap](https://user-images.githubusercontent.com/5550310/133043862-3717a9a6-d6cf-4684-9244-0c6346a19d99.png)

**Comment by kangalioo** [comment]
Weird, that must be an issue with your Discord client

This is what it looks like for me: ![screenshot](https://media.discordapp.net/attachments/273541645579059201/886880923302371378/Screenshot_2021-09-13-09-45-25-116_com.discord.jpg)

**Comment by HeroicKatora** [comment]
Just found out—it's a setting in the client (confusingly named). In 'Text & Image' there is 'Preview Websites…' which—when toggled off because I don't like the automatic embeds from multiple standpoints—apparently turns off _all_ embeds. Including those generated by the bot.

**Comment by kangalioo** [comment]
I see, that's unfortunate.

Apart from that, are there other things you think could be improved about the showcase command?

**Comment by kangalioo** [comment]
I improved the command again. In `?help` and in Discord's slash command list it now says

> Asks details about your project and then posts it in the #showcase channel

And `?help showcase` says

> Starts a prompt where you can enter information about a project you're working on. The bot will then post your project into the #showcase channel and open a thread to allow for discussion and feedback.
> 
> If you want to change the text later, edit your message and the bot will propagate the change.
> You can also delete your message to delete the #showcase entry.

When invoking `/showcase` or `?showcase`, the bot now says as the first thing:

> Answer the following prompts to generate a #showcase entry. If you change your mind later, you can edit or delete your messages, and the #showcase entry will be edited or deleted accordingly.

Which is good because the user doesn't have to be afraid of messing up in the subsequent prompts, knowing that they can fix their mistakes. (Also, Discord will render subsequent prompts to refer to this introduction message instead of to `Please enter the name of the project:`, which makes more sense)
