### ISSUE TITLE
Nightly used when 2021 edition is specified no matter what channel

### ISSUE THREAD

**Issue by Ben-Lichtman** [kangalioo/rustbot#26]
for example: 
?eval channel=stable
```rust
#![feature(iter_zip)]
```
gives
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:1:1
  |
1 | #![feature(iter_zip)]
  | ^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
```
but

?eval channel=stable edition=2021 
```rust
#![feature(iter_zip)]
```
gives:

```
()
```

**Comment by kangalioo** [comment]
The Rust community server is running an old version from a time where 2021 edition was only available on nightly:

https://github.com/kangalioo/rustbot/blob/fc09bafa87a6356f35a7974c0db073e9b71ff318/src/playground/play_eval.rs#L25-L30

This code was since removed by #22, when 2021 edition reached stable ([relevant part of commit](https://github.com/kangalioo/rustbot/commit/abc442e9bac7e0bd07a73bd72de03a86350ae057#diff-f26733f48195ec36e0f76de558f3a7d87fbf5cf9ab9bab3d557be9e1b449dad6L25-L30)).
